# Generated by Django 2.0 on 2018-01-13 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionpart',
            name='spacing',
        ),
        migrations.RemoveField(
            model_name='singlequestion',
            name='spacing',
        ),
    ]
