# Generated by Django 2.0 on 2018-01-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpart',
            name='spacing',
            field=models.CharField(default='1in', max_length=254),
            preserve_default=False,
        ),
    ]
