# Generated by Django 2.0 on 2018-01-12 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('number', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Worksheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('description', models.CharField(blank=True, max_length=254, null=True)),
                ('date', models.DateField()),
                ('question_order', models.CharField(blank=True, max_length=254)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worksheets.Course')),
                ('questions', models.ManyToManyField(blank=True, to='questions.Question')),
            ],
        ),
        migrations.CreateModel(
            name='WorksheetFormatBlock',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questions.Block')),
            ],
            bases=('questions.block',),
        ),
        migrations.CreateModel(
            name='WFBDirections',
            fields=[
                ('worksheetformatblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='worksheets.WorksheetFormatBlock')),
                ('directions', models.TextField()),
            ],
            bases=('worksheets.worksheetformatblock',),
        ),
        migrations.CreateModel(
            name='WFBNewPage',
            fields=[
                ('worksheetformatblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='worksheets.WorksheetFormatBlock')),
            ],
            bases=('worksheets.worksheetformatblock',),
        ),
    ]
