# Generated by Django 2.0 on 2018-01-13 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wfbnewpage',
            name='worksheetformatblock_ptr',
        ),
        migrations.AddField(
            model_name='worksheetformatblock',
            name='latex_code',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='WFBNewPage',
        ),
    ]
