# Generated by Django 2.0 on 2018-01-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheets', '0002_auto_20180103_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksheet',
            name='questions',
            field=models.ManyToManyField(blank=True, null=True, to='questions.Question'),
        ),
    ]
