# Generated by Django 2.0 on 2018-01-13 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheets', '0002_auto_20180112_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksheetformatblock',
            name='latex_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
