# Generated by Django 2.0 on 2018-01-13 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
        ('worksheets', '0003_auto_20180112_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worksheet',
            old_name='question_order',
            new_name='block_order',
        ),
        migrations.RemoveField(
            model_name='worksheet',
            name='questions',
        ),
        migrations.AddField(
            model_name='worksheet',
            name='blocks',
            field=models.ManyToManyField(blank=True, to='questions.Block'),
        ),
    ]
