# Generated by Django 2.0 on 2018-01-04 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheets', '0006_auto_20180103_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksheet',
            name='question_order',
            field=models.CharField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
