# Generated by Django 2.0 on 2018-01-05 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worksheets', '0008_auto_20180104_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksheet',
            name='description',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
