# Generated by Django 2.0 on 2018-01-05 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worksheets', '0009_auto_20180104_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksheet',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='worksheets.Course'),
        ),
    ]
